version: '3.9' 

services:

  postgres:

    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - ./env/.postgres_env
    networks:
      - dockerized_django_net
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    restart: unless-stopped  


  adminer:
        image: adminer
        environment:
            - ADMINER_DESIGN=pappu687
        depends_on:
            - postgres
        networks:
            - dockerized_django_net
        volumes:
            - adminer:/adminer
        ports:
            - 8080:8080
        restart: on-failure


  django:

    build:
      context: ./django/
      dockerfile: 'DockerFile'
    

      


    depends_on:
      - postgres 

    volumes:
        - ./django:/app
        - static-files:/app/assets

    links:
      - postgres:postgres

    ports:
      - 5000:5000

    env_file:
      - ./env/.env

    networks:
      - dockerized_django_net  


    restart: always


volumes:
    static-files:
        name: videoapp_django_static_volume
    postgresdata:
        name: videoapp_postgres_volume

    adminer:
        name: videoapp_adminer_volume    
    




networks:
    dockerized_django_net:
        name: supernet
        external: True    





            