# Generated by Django 5.1.4 on 2024-12-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_date_of_birth_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='accounts.patientprofile'),
        ),
    ]
