# Generated by Django 5.1.4 on 2025-01-16 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0003_alter_doctorprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='hospital',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Hospital'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to=settings.AUTH_USER_MODEL),
        ),
    ]
